parameters:
#    ftfs_preference.example.class: FTFS\PreferenceBundle\Example

services:
#    ftfs_preference.example:
#        class: %ftfs_preference.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    ftfs_configurator:
        class:  FTFS\PreferenceBundle\Container\Configurator
        arguments:  [@doctrine.orm.entity_manager]
