FTFSSystemBundle:
    resource: "@FTFSSystemBundle/Resources/config/routing.yml"
    prefix:   /

################## general json entry point
##############3
FTFSProductBundle:
    resource: "@FTFSProductBundle/Resources/config/routing.yml"
    prefix:   /admin/{_locale}/product
    defaults: {_locale: en}

FTFSAssetBundle:
    resource: "@FTFSAssetBundle/Resources/config/routing.yml"
    prefix:   /admin/{_locale}/asset
    defaults: {_locale: en}

# homepage of ftfs, routing to dashboardbundle:default:index by default,
# to be updated in the prod version
ftfshomepage:
    pattern:  /
    defaults: { _controller: FTFSDashboardBundle:Default:index }


#############################################################################
FTFSDashboardBundle:
    resource: "@FTFSDashboardBundle/Resources/config/routing.yml"
    prefix:   /dashboard/{_locale}
    defaults: {_locale: en}

FTFSUserBundle:
    resource: "@FTFSUserBundle/Resources/config/routing/user_routing.yml"
    prefix:   /admin/{_locale}/user
    defaults: {_locale: en}

FTFSUserBundle_role:
    resource: "@FTFSUserBundle/Resources/config/routing/role_routing.yml"
    prefix:   /admin/{_locale}/role
    defaults: {_locale: en}

FTFSServiceBundle:
    resource: "@FTFSServiceBundle/Resources/config/routing.yml"
    prefix:   /admin/{_locale}/service
    defaults: {_locale: en}

# fos_userbundle routing rules
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

#fos_user_group:
#    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
#    prefix: /admin/group

FTFSNotificationBundle:
    resource: "@FTFSNotificationBundle/Resources/config/routing.yml"
    prefix:   /

FTFSPreferenceBundle:
    resource: "@FTFSPreferenceBundle/Resources/config/routing.yml"
    prefix:   /admin/{_locale}/preference
    defaults: {_locale: en}

FTFSPreferenceBundle_user:
    resource: "@FTFSPreferenceBundle/Resources/config/user_preference_routing.yml"
    prefix:   /dashboard/{_locale}/preference
    defaults: {_locale: en}


# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
