FTFSProductBundle:
    resource: "@FTFSProductBundle/Resources/config/routing.yml"
    prefix:   /admin/product

FTFSAssetBundle:
    resource: "@FTFSAssetBundle/Resources/config/routing.yml"
    prefix:   /admin/asset

# homepage of ftfs, routing to dashboardbundle:default:index by default,
# to be updated in the prod version
ftfshomepage:
    pattern:  /
    defaults: { _controller: FTFSDashboardBundle:Default:index }


#############################################################################
FTFSDashboardBundle:
    resource: "@FTFSDashboardBundle/Resources/config/routing.yml"
    prefix:   /dashboard

FTFSUserBundle:
    resource: "@FTFSUserBundle/Resources/config/routing/user_routing.yml"
    prefix:   /admin/user

FTFSUserBundle_role:
    resource: "@FTFSUserBundle/Resources/config/routing/role_routing.yml"
    prefix:   /admin/role

FTFSServiceBundle:
    resource: "@FTFSServiceBundle/Resources/config/routing.yml"
    prefix:   /admin/service

# fos_userbundle routing rules
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

#fos_user_group:
#    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
#    prefix: /admin/group

FTFSNotificationBundle:
    resource: "@FTFSNotificationBundle/Resources/config/routing.yml"

FTFSPreferenceBundle:
    resource: "@FTFSPreferenceBundle/Resources/config/routing.yml"
    prefix:   /admin/preference

FTFSPreferenceBundle_user:
    resource: "@FTFSPreferenceBundle/Resources/config/user_preference_routing.yml"
    prefix:   /dashboard/preference


# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
