security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        "FOS\UserBundle\Model\UserInterface":   sha512

    providers:
#        fos_userbundle:
#            id: fos_user.user_manager
        custom:
            id: ftfs_user.user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:    ^/(login$|register|resetting)
            #security: false
            anonymous:  true

        main:
            pattern:    ^/
            form_login:
                #provider:   fos_userbundle
                provider:   custom
                csrf_provider: form.csrf_provider
            logout:     true
            anonymous:  false 
            remember_me:
                key:    %secret%
            #######################################only for dev to be deleted ...
            switch_user: { role: ROLE_ALLOWED_TO_SWITCH, parameter: _su } 

    access_control:
       # - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       # - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       # - { path: ^/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/dashboard/, roles: [ROLE_CLIENT, ROLE_AGENT] }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }

    role_hierarchy:
        ROLE_AGENT:       ROLE_USER
        ROLE_CLIENT:      ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

