FTFSUserBundle_management_index:
    pattern:  /user
    defaults: { _controller: FTFSUserBundle:UserManagement:index }

FTFSUserBundle_management_show:
    pattern:  /user/show
    defaults: { _controller: FTFSUserBundle:UserManagement:index }

FTFSUserBundle_management_edit:
    pattern:  /user/edit
    defaults: { _controller: FTFSUserBundle:UserManagement:index }

