services:
    ftfs_user.registration.form.type:
        class:  FTFS\UserBundle\Form\Type\RegistrationFormType
        arguments:  [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: ftfs_user_registration }

    ftfs_user.profile.form.type:
        class:  FTFS\UserBundle\Form\Type\ProfileFormType
        arguments:  [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: ftfs_user_profile }
