## all user
ftfs_notificationbundle_user_index:
    pattern:  /user/{_locale}/notification/index
    defaults: { _controller: FTFSNotificationBundle:User:index, _locale: en}

ftfs_notificationbundle_user_clear_system_notification:
    pattern:  /user/{_locale}/notification/clear
    defaults: { _controller: FTFSNotificationBundle:User:systemNotificationClear, _locale: en}

ftfs_notificationbundle_user_remove_system_notification:
    pattern:  /user/{_locale}/notification/remove/{id}
    defaults: { _controller: FTFSNotificationBundle:User:systemNotificationRemove, _locale: en}

# ajax url for count filter
ftfs_notificationbundle_user_get_one_notification:
    pattern:  /user/{_locale}/notification/get_one_notification
    defaults: { _controller: FTFSNotificationBundle:User:getOneNotification, _locale: en}

ftfs_notificationbundle_user_get_notification_count:
    pattern:  /user/{_locale}/notification/get_notification_count
    defaults: { _controller: FTFSNotificationBundle:User:getNotificationCount, _locale: en}

## preference
ftfs_notificationbundle_preference_event_definition:
    pattern:  /admin/{_locale}/preference/notification/event_definition
    defaults: { _controller: FTFSNotificationBundle:Preference:eventDefinition, _locale: en}

ftfs_notificationbundle_preference_method_enable:
    pattern:  /admin/{_locale}/preference/notification/method/{id}/enable/for/{for}
    defaults: { _controller: FTFSNotificationBundle:Preference:methodEnable, _locale: en}

ftfs_notificationbundle_preference_method_disable:
    pattern:  /admin/{_locale}/preference/notification/method/{id}/disable/for/{for}
    defaults: { _controller: FTFSNotificationBundle:Preference:methodDisable, _locale: en}

ftfs_notificationbundle_preference_event_add:
    pattern:  /admin/{_locale}/preference/notification/event_add
    defaults: { _controller: FTFSNotificationBundle:Preference:eventAdd, _locale: en}

ftfs_notificationbundle_preference_event_catch_filter_default:
    pattern:  /admin/{_locale}/preference/notification/event_catch_filter_default/{id}/{auto}
    defaults: { _controller: FTFSNotificationBundle:Preference:eventCatchFilterDefault, _locale: en}

## personal preferences for all user
ftfs_notificationbundle_preference_event_catch_filter_index:
    pattern:  /user/{_locale}/preference/{id}/notification/event_catch_filter
    defaults: { _controller: FTFSNotificationBundle:Preference:eventCatchFilterList, _locale: en}

ftfs_notificationbundle_preference_event_catch_filter_reset:
    pattern:  /user/{_locale}/preference/{id}/notification/event_catch_filter/resetting
    defaults: { _controller: FTFSNotificationBundle:Preference:eventCatchFilterReset, _locale: en}

ftfs_notificationbundle_preference_event_catch_filter:
    pattern:  /user/{_locale}/preference/{id}/notification/event_catch_filter/{event_id}/{auto}
    defaults: { _controller: FTFSNotificationBundle:Preference:eventCatchFilter, _locale: en}
