services:
    ftfs_notification.notifier.event_registration_notifier:
        class:  FTFS\NotificationBundle\Container\Notifier\EventRegistrationNotifier
        arguments:  [@doctrine.orm.entity_manager]

    ftfs_notification.notifier.event_notification_notifier:
        class:  FTFS\NotificationBundle\Container\Notifier\EventNotificationNotifier
        arguments:  [@doctrine.orm.entity_manager, @templating]

    ftfs_notification.listener.event_registration_listener:
        class:  FTFS\NotificationBundle\Container\Listener\EventRegistrationListener
        arguments:  [@service_container]
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    ftfs_notification.sender.agent.email:
        class:  FTFS\NotificationBundle\Sender\Agent\EmailAgent
        arguments:  [@mailer]
        tags:
            - { name: merk_notification.sender.agent, alias: email }
