ftfsuserbundle_user_index:
    pattern:  /
    defaults: { _controller: FTFSUserBundle:User:index }

ftfsuserbundle_user_show:
    pattern:  /{username}/show
    defaults: { _controller: FTFSUserBundle:User:show }

ftfsuserbundle_user_edit:
    pattern:  /{username}/edit
    defaults: { _controller: FTFSUserBundle:User:edit }

ftfsuserbundle_user_edit_roles:
    pattern:  /{username}/edit_roles
    defaults: { _controller: FTFSUserBundle:User:editRoles }

ftfsuserbundle_user_edit_password:
    pattern:  /{username}/edit_password
    defaults: { _controller: FTFSUserBundle:User:editPassword }

ftfsuserbundle_user_invite:
    pattern:  /invite
    defaults: { _controller: FTFSUserBundle:User:invite }

