FTFSUserBundle_user_index:
    pattern:  /
    defaults: { _controller: FTFSUserBundle:User:index }

FTFSUserBundle_user_show:
    pattern:  /{username}
    defaults: { _controller: FTFSUserBundle:User:show }

FTFSUserBundle_user_edit:
    pattern:  /{username}/edit
    defaults: { _controller: FTFSUserBundle:User:edit }

FTFSUserBundle_user_edit_group:
    pattern:  /{username}/edit_group
    defaults: { _controller: FTFSUserBundle:User:editGroup }

FTFSUserBundle_user_edit_password:
    pattern:  /{username}/edit_password
    defaults: { _controller: FTFSUserBundle:User:editPassword }
