ftfs_servicebundle_homepage:
    pattern:  /
    defaults: { _controller: FTFSServiceBundle:Default:index }

## service ticket ##############################################################
#
ftfs_servicebundle_serviceticket_index:
    pattern:  /ticket/list
    defaults: { _controller: FTFSServiceBundle:ServiceTicket:index }

ftfs_servicebundle_serviceticket_new:
    pattern:  /ticket/new
    defaults: { _controller: FTFSServiceBundle:ServiceTicket:new }

ftfs_servicebundle_serviceticket_show:
    pattern:  /ticket/{id}/show
    defaults: { _controller: FTFSServiceBundle:ServiceTicket:show }

ftfs_servicebundle_serviceticket_edit:
    pattern:  /ticket/{id}/edit
    defaults: { _controller: FTFSServiceBundle:ServiceTicket:edit }

ftfs_servicebundle_serviceticket_delete:
    pattern:  /ticket/{id}/delete
    defaults: { _controller: FTFSServiceBundle:ServiceTicket:delete }

ftfs_servicebundle_serviceticket_assign:
    pattern:  /ticket/{id}/assign
    defaults: { _controller: FTFSServiceBundle:ServiceTicket:show }

## service definition #########################################################
#
ftfs_servicebundle_service_index:
    pattern:  /define/list
    defaults: { _controller: FTFSServiceBundle:Service:index }

ftfs_servicebundle_service_new:
    pattern:  /define/new
    defaults: { _controller: FTFSServiceBundle:Service:new }

ftfs_servicebundle_service_show:
    pattern:  /define/{id}/show
    defaults: { _controller: FTFSServiceBundle:Service:show }

ftfs_servicebundle_service_edit:
    pattern:  /define/{id}/edit
    defaults: { _controller: FTFSServiceBundle:Service:edit }

ftfs_servicebundle_service_delete:
    pattern:  /define/{id}/delete
    defaults: { _controller: FTFSServiceBundle:Service:delete }

ftfs_servicebundle_service_activate:
    pattern:  /define/{id}/activate
    defaults: { _controller: FTFSServiceBundle:Service:activate }
