ftfs_servicebundle_homepage:
    #pattern:  /
    #defaults: { _controller: FTFSServiceBundle:Default:index }
    pattern:  /ticket/list
    defaults: { _controller: FTFSServiceBundle:ServiceTicket:index }

## service ticket ##############################################################
#
ftfs_servicebundle_serviceticket_index:
    pattern:  /ticket/list
    defaults: { _controller: FTFSServiceBundle:ServiceTicket:index }

ftfs_servicebundle_serviceticket_new:
    pattern:  /ticket/new
    defaults: { _controller: FTFSServiceBundle:ServiceTicket:new }

ftfs_servicebundle_serviceticket_show:
    pattern:  /ticket/{id}/show
    defaults: { _controller: FTFSServiceBundle:ServiceTicket:show }

ftfs_servicebundle_serviceticket_edit:
    pattern:  /ticket/{id}/edit
    defaults: { _controller: FTFSServiceBundle:ServiceTicket:edit }

ftfs_servicebundle_serviceticket_delete:
    pattern:  /ticket/{id}/delete
    defaults: { _controller: FTFSServiceBundle:ServiceTicket:delete }

ftfs_servicebundle_serviceticket_assign:
    pattern:  /ticket/{id}/assign
    defaults: { _controller: FTFSServiceBundle:ServiceTicket:show }

## attachment
ftfs_servicebundle_serviceticket_attachment_upload:
    pattern:  /ticket/{id}/attachment/upload
    defaults: { _controller: FTFSServiceBundle:ServiceTicket:attachmentUpload }

ftfs_servicebundle_serviceticket_attachment_download:
    pattern:  /ticket/{id}/attachment/download/{attachment_id}
    defaults: { _controller: FTFSServiceBundle:ServiceTicket:attachmentDownload }

ftfs_servicebundle_serviceticket_attachment_delete:
    pattern:  /ticket/{id}/attachment/delete/{attachment_id}
    defaults: { _controller: FTFSServiceBundle:ServiceTicket:attachmentDelete }

## observation
ftfs_servicebundle_serviceticket_observation_add:
    pattern:  /ticket/{id}/observation/add
    defaults: { _controller: FTFSServiceBundle:ServiceTicket:observationAdd }

## service definition #########################################################
#
ftfs_servicebundle_service_index:
    pattern:  /define/list
    defaults: { _controller: FTFSServiceBundle:Service:index }

ftfs_servicebundle_service_new:
    pattern:  /define/new
    defaults: { _controller: FTFSServiceBundle:Service:new }

ftfs_servicebundle_service_show:
    pattern:  /define/{id}/show
    defaults: { _controller: FTFSServiceBundle:Service:show }

ftfs_servicebundle_service_edit:
    pattern:  /define/{id}/edit
    defaults: { _controller: FTFSServiceBundle:Service:edit }

ftfs_servicebundle_service_delete:
    pattern:  /define/{id}/delete
    defaults: { _controller: FTFSServiceBundle:Service:delete }

ftfs_servicebundle_service_activate:
    pattern:  /define/{id}/activate
    defaults: { _controller: FTFSServiceBundle:Service:activate }
