ftfs_servicebundle_homepage:
    pattern:  /
    defaults: { _controller: FTFSServiceBundle:Default:index }

## service ticket ##############################################################
#
ftfs_servicebundle_service_index:
    pattern:  /list
    defaults: { _controller: FTFSServiceBundle:Service:index }

ftfs_servicebundle_service_new:
    pattern:  /new
    defaults: { _controller: FTFSServiceBundle:Service:new }

ftfs_servicebundle_service_show:
    pattern:  /show/{id}
    defaults: { _controller: FTFSServiceBundle:Service:show }

ftfs_servicebundle_service_edit:
    pattern:  /edit/{id}
    defaults: { _controller: FTFSServiceBundle:Service:edit }

ftfs_servicebundle_service_delete:
    pattern:  /delete/{id}
    defaults: { _controller: FTFSServiceBundle:Service:delete }

## service type ##############################################################
#
ftfs_servicebundle_servicetype_index:
    pattern:  /type/list
    defaults: { _controller: FTFSServiceBundle:ServiceType:index }

ftfs_servicebundle_servicetype_new:
    pattern:  /type/new
    defaults: { _controller: FTFSServiceBundle:ServiceType:new }

ftfs_servicebundle_servicetype_show:
    pattern:  /type/show/{id}
    defaults: { _controller: FTFSServiceBundle:ServiceType:show }

ftfs_servicebundle_servicetype_edit:
    pattern:  /type/edit/{id}
    defaults: { _controller: FTFSServiceBundle:ServiceType:edit }

ftfs_servicebundle_servicetype_delete:
    pattern:  /type/delete/{id}
    defaults: { _controller: FTFSServiceBundle:ServiceType:delete }

## service request ############################################################
#
ftfs_servicebundle_servicerequest_index:
    pattern:  /request/list
    defaults: { _controller: FTFSServiceBundle:ServiceRequest:index }

ftfs_servicebundle_servicerequest_new:
    pattern:  /request/new
    defaults: { _controller: FTFSServiceBundle:ServiceRequest:new }

ftfs_servicebundle_servicerequest_show:
    pattern:  /request/show/{id}
    defaults: { _controller: FTFSServiceBundle:ServiceRequest:show }

ftfs_servicebundle_servicerequest_edit:
    pattern:  /request/edit/{id}
    defaults: { _controller: FTFSServiceBundle:ServiceRequest:edit }

ftfs_servicebundle_servicerequest_delete:
    pattern:  /request/delete/{id}
    defaults: { _controller: FTFSServiceBundle:ServiceRequest:delete }

