parameters:
#    ftfs_service.example.class: FTFS\ServiceBundle\Example

services:
    ftfs_servicebundle.name_generator:
        class: FTFS\ServiceBundle\Container\NameGenerator
        ##arguments: []
        #
