parameters:
#    ftfs_service.example.class: FTFS\ServiceBundle\Example

services:
#    ftfs_service.example:
#        class: %ftfs_service.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
