parameters:
#    ftfs_crud.example.class: FTFS\CrudBundle\Example

services:
#    ftfs_crud.example:
#        class: %ftfs_crud.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
