parameters:
#    ftfs_asset.example.class: FTFS\AssetBundle\Example

services:
#    ftfs_asset.example:
#        class: %ftfs_asset.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
